### ISSUE TITLE
Crash on Android 6

### ISSUE THREAD

**Issue by amarkovits** [tanersener/mobile-ffmpeg#158]
**Description**
My app is crashing on android 6 when using this library

**Logs**
`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memcpy" referenced by "/data/app/mypackagename/lib/arm/libmobileffmpeg-abidetect.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.arthenica.mobileffmpeg.AbiDetect.<clinit>(AbiDetect.java:33)
        at com.arthenica.mobileffmpeg.AbiDetect.getNativeCpuAbi(Native Method)
        at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:89)`

**Environment**
 - Platform: Android
 - Architecture: arm-v7a
 - Version  4.2.1

**Comment by amarkovits** [comment]
nevermind, just realised I have to use the LTS version because the main version is for android 24+
