### ISSUE TITLE
Couldn't load mobileffmpeg-abidetect from loader dalvik.system.PathClassLoader

### ISSUE THREAD

**Issue by rahulpawar1989** [tanersener/mobile-ffmpeg#176]
**Description**
In my HTC desire 629G dual sim, when i add your library as Module and run my Android application i get below error

07-05 14:35:13.518 19425-19425/com.outthinking.videomerge E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.outthinking.videomerge, PID: 19425
    java.lang.UnsatisfiedLinkError: Couldn't load mobileffmpeg_abidetect from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.outthinking.videomerge-2.apk", zip file "/data/data/com.outthinking.videomerge/code_cache/secondary-dexes/com.outthinking.videomerge-2.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/com.outthinking.videomerge-2, /vendor/lib, /system/lib]]]: findLibrary returned null
        at java.lang.Runtime.loadLibrary(Runtime.java:365)
        at java.lang.System.loadLibrary(System.java:606)
        at com.arthenica.mobileffmpeg.AbiDetect.<clinit>(AbiDetect.java:33)
        at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:89)
        at com.outthinking.videomerge.ShowVideoInGrid.enableLogCallback(ShowVideoInGrid.java:1386)
        at com.outthinking.videomerge.ShowVideoInGrid.setActive(ShowVideoInGrid.java:1380)
        at com.outthinking.videomerge.ShowVideoInGrid.onCreate(ShowVideoInGrid.java:230)
        at android.app.Activity.performCreate(Activity.java:5343)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5333)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
        at dalvik.system.NativeStart.main(Native Method)

**Environment**
 - Platform: Android 4.4.2
 - Version 4.2.2.LTS
 - Android Studio version  3.4

**Comment by tanersener** [comment]
Can you provide ABI information and API Level of your device?

**Comment by tanersener** [comment]
@rahulpawar1989 Could you please give an update about this issue. Is it resolved?

**Comment by rahulpawar1989** [comment]
sorry for the late reply.

I don't know what happened but after restarting my device and android studio now its working.

Thanks for the reply.

**Comment by tanersener** [comment]
Great 👍. Thank you for letting me know.
