### ISSUE TITLE
Creating Android archive under prebuilt/android-aar: failed

### ISSUE THREAD

**Issue by mgood7123** [tanersener/mobile-ffmpeg#396]
**Description**
Creating Android archive under prebuilt/android-aar: failed

**Expected behavior**
Creating Android archive under prebuilt/android-aar: ok

**Current behavior**
Creating Android archive under prebuilt/android-aar: failed

**Screenshots**

**Logs**
```
[x86_64] Install        : libswresample.so => libs/x86_64/libswresample.so
[x86_64] Install        : libavdevice.so => libs/x86_64/libavdevice.so
[x86_64] Install        : libswscale.so => libs/x86_64/libswscale.so
Downloading https://services.gradle.org/distributions/gradle-6.0.1-bin.zip

Exception in thread "main" javax.net.ssl.SSLException: Received fatal alert: protocol_version
	at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:190)
	at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:136)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1822)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1004)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1188)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1215)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1199)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:476)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:166)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1195)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:234)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:67)
	at org.gradle.wrapper.Download.download(Download.java:52)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:62)
```

**Environment**
 - Platform: Android
 - Architecture: N/A
 - Version (if applicable) mobile-ffmpeg v4.3.2-17-g904e9def3
 - Source branch (if applicable) mobile-ffmpeg v4.3.2-17-g904e9def3
 - Xcode version (if applicable) 10.3
 - Cocoapods version (if applicable) [e.g. 1.2.1]
 - Android Studio version (if applicable) 4.0
 - Android NDK version (if applicable) 20.0.6

**Other**

**Comment by tanersener** [comment]
```
Downloading https://services.gradle.org/distributions/gradle-6.0.1-bin.zip

Exception in thread "main" javax.net.ssl.SSLException: Received fatal alert: protocol_version
```

This error is not about this project. It is an SSL error received when `gradle` is being downloaded.
