### ISSUE TITLE
App crash with error message - couldn't find "libmobileffmpeg_abidetect.so"

### ISSUE THREAD

**Issue by chitrang200889** [tanersener/mobile-ffmpeg#497]
**Description**
For certain devices, app crashes when the application is uploaded as .aab

```
bundle {
        density {
            enableSplit false
        }
        language {
            enableSplit false
        }
        abi {
            enableSplit true
        }
    }
```

**Devices**

- Samsung Galaxy Note10 5G (OS 5.1.1)
- Meizu U10 (OS 6.0)
- TECNO 7C (OS 5.0)

**Expected behavior**
The app shouldn't crash.

**Current behavior**
The app is crashing when loading mobile-ffmpeg library

**Logs**

```
Caused by java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/a.b.com-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libmobileffmpeg_abidetect.so"
       at java.lang.Runtime.loadLibrary(Runtime.java:366)
       at java.lang.System.loadLibrary(System.java:989)
       at com.arthenica.mobileffmpeg.AbiDetect.<clinit>(AbiDetect.java:40)
       at com.arthenica.mobileffmpeg.AbiDetect.getNativeAbi(AbiDetect.java)
       at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:111)
       at com.arthenica.mobileffmpeg.FFmpeg.execute(FFmpeg.java:56)
       at a.b.com.media.libffmpeg.FfmpegProcessor$runAsyncCommandObservable$1.subscribe(FfmpegProcessor.kt:30)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
       at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:52)
       at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn.subscribeActual(FlowableObserveOn.java:56)
       at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
       at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15686)
       at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15647)
       at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
       at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
       at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
       at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
       at android.os.Handler.handleCallback(Handler.java:810)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:189)
       at android.app.ActivityThread.main(ActivityThread.java:5529)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
```

**Environment**
 - Platform: Android
 - Architecture: arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64
 - Version: implementation 'com.arthenica:mobile-ffmpeg-full-gpl:4.3.1.LTS'

**Comment by umaqs** [comment]
hi @chitrang200889 

I am facing the same problem in my flutter app. have you found any solution?

This is the stack-trace I see:

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/app.domain.name-Lq_GxP1CfMArHTpLoII-YA==/base.apk"],nativeLibraryDirectories=[/data/app/app.domain.name-Lq_GxP1CfMArHTpLoII-YA==/lib/arm64, /data/app/app.domain.name-Lq_GxP1CfMArHTpLoII-YA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libmobileffmpeg_abidetect.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.arthenica.mobileffmpeg.AbiDetect.<clinit>(Unknown Source:13)
        at com.arthenica.mobileffmpeg.AbiDetect.getNativeAbi(Native Method)
        at com.arthenica.mobileffmpeg.Config.<clinit>(Unknown Source:96)
        at com.arthenica.mobileffmpeg.Config.nativeFFmpegExecute(Native Method)
        at com.arthenica.mobileffmpeg.b.a(Unknown Source:0)
        at d.b.a.a.a.a(Unknown Source:31)
        at d.b.a.a.a.doInBackground(Unknown Source:2)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by chitrang200889** [comment]
Have you uploaded as app bunle .aab file or .apk? Also, do you see any pattern for device types or OS versions?

**Comment by tanersener** [comment]
This library does not provide an `.aab` file. This issue can't be caused by `mobile-ffmpeg` archives.

**Comment by chitrang200889** [comment]
We have used this library as gradle only. But when we upload app on Google Play Console we upload as single .aab file instead of split APKs.

**Comment by tanersener** [comment]
This is a packaging issue. What you need to do it:

- Check which ABI is used by those devices
- Look inside the `aab` file created and see whether `mobile-ffmpeg` native libraries are there for that ABI

**Comment by umaqs** [comment]
I am using flutter-ffmpeg and for me, it was some Android studio bug where the file was not getting copied to the .aab. 
[have a look at my original issue](https://github.com/tanersener/flutter-ffmpeg/issues/198)

**Comment by inventionsbyhamid** [comment]
We also faced a similar issue, upgrading the android gradle plugin and gradle wrapper distribution fixed the problem for us.

**Comment by chitrang200889** [comment]
@inventionsbyhamid Can you please share which exact versions solved your problem?

**Comment by inventionsbyhamid** [comment]
We are now using following versions:
Android gradle plugin - com.android.tools.build:gradle:4.1.1
Gradle wrapper - 6.5

Earlier (when it was crashing):
Android gradle plugin - com.android.tools.build:gradle:3.5.3
Gradle wrapper - 5.4.1

mobile-ffmpeg verison being used com.arthenica:mobile-ffmpeg-audio:4.3.1.LTS
