### ISSUE TITLE
Cannot build on Android

### ISSUE THREAD

**Issue by iamprogramer** [tanersener/mobile-ffmpeg#537]
**Description**
Hello, this is very useful project. I am try to build it on Android and it worked when i use:
//     implementation project(':app')
    implementation 'com.arthenica:mobile-ffmpeg-full:4.4.LTS'

But when i try 
    implementation project(':app')
//     implementation 'com.arthenica:mobile-ffmpeg-full:4.4.LTS'

It is not work. Could you help me, Please, thank you!

**Logs**
Process: com.arthenica.mobileffmpeg.test, PID: 27197
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.arthenica.mobileffmpeg.test-zoanyGXbwgnfaNVdQiIEwg==/base.apk"],nativeLibraryDirectories=[/data/app/com.arthenica.mobileffmpeg.test-zoanyGXbwgnfaNVdQiIEwg==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libmobileffmpeg_abidetect.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.arthenica.mobileffmpeg.AbiDetect.<clinit>(AbiDetect.java:33)
        at com.arthenica.mobileffmpeg.AbiDetect.getNativeAbi(Native Method)
        at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:131)
        at com.arthenica.mobileffmpeg.Config.setFontDirectory(Config.java:357)
        at com.arthenica.mobileffmpeg.test.MainActivity.registerAppFont(MainActivity.java:177)
        at com.arthenica.mobileffmpeg.test.MainActivity.onCreate(MainActivity.java:130)

**Comment by HBiSoft** [comment]
You need to compile the libraries first.

Have a look at the Readme - https://github.com/tanersener/mobile-ffmpeg#52-build-scripts
