### ISSUE TITLE
Cannot locate symbol "__register_atfork"

### ISSUE THREAD

**Issue by YunlongYang** [tanersener/mobile-ffmpeg#572]
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "/data/app/com.pencilstub.pieces-1/lib/arm64/libmobileffmpeg_abidetect.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:988)
        at com.arthenica.mobileffmpeg.AbiDetect.<clinit>(AbiDetect.java:33)
        at com.arthenica.mobileffmpeg.AbiDetect.getNativeAbi(Native Method)
        at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:131)
        at com.arthenica.mobileffmpeg.FFmpeg.execute(FFmpeg.java:68)
        at com.arthenica.mobileffmpeg.FFmpeg.execute(FFmpeg.java:129)

**Comment by YunlongYang** [comment]
Android 5.1 api 22

**Comment by YunlongYang** [comment]
move to #575
