### ISSUE TITLE
Native crash: dlopen failed: cannot locate symbol "__register_atfork"

### ISSUE THREAD

**Issue by YunlongYang** [tanersener/mobile-ffmpeg#575]
**Description**
When execute FFmpeg command on Android 5.0, app crash

**Expected behavior**
What you expected to happen.

**Current behavior**
app crash when execute FFmpeg command

**Screenshots**
none

**Logs**
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "/data/app/com.pencilstub.pieces-1/lib/arm64/libmobileffmpeg_abidetect.so"...
at java.lang.Runtime.loadLibrary(Runtime.java:372)
at java.lang.System.loadLibrary(System.java:988)
at com.arthenica.mobileffmpeg.AbiDetect.(AbiDetect.java:33)
at com.arthenica.mobileffmpeg.AbiDetect.getNativeAbi(Native Method)
at com.arthenica.mobileffmpeg.Config.(Config.java:131)
at com.arthenica.mobileffmpeg.FFmpeg.execute(FFmpeg.java:68)
at com.arthenica.mobileffmpeg.FFmpeg.execute(FFmpeg.java:129)

**Environment**
 - Platform: [Android 5.0]
 - Architecture: [arm64-v8a]
 - Version (if applicable) [e.g. v1.2]

**Other**
none

**Comment by tanersener** [comment]
Marked as `missing-issue-template` due to missing version and package information.
