### ISSUE TITLE
How can i play audio preview on the fly?

### ISSUE THREAD

**Issue by iamkdblue** [tanersener/mobile-ffmpeg#630]
Thanks for this great library!

**Description**
I am trying SDL branch for ffplay but I am getting crash!

**Current behavior**
```
    --------- beginning of crash
2020-12-25 12:23:13.808 18855-18855/com.arthenica.mobileffmpeg.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.arthenica.mobileffmpeg.test, PID: 18855
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.arthenica.mobileffmpeg.test-hp8FHjNb_TMmoMDru9h9mw==/base.apk"],nativeLibraryDirectories=[/data/app/com.arthenica.mobileffmpeg.test-hp8FHjNb_TMmoMDru9h9mw==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libmobileffmpeg_abidetect.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.arthenica.mobileffmpeg.AbiDetect.<clinit>(AbiDetect.java:40)
        at com.arthenica.mobileffmpeg.AbiDetect.getNativeAbi(Native Method)
        at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:112)
        at com.arthenica.mobileffmpeg.Config.setFontDirectory(Config.java:338)
        at com.arthenica.mobileffmpeg.test.MainActivity.registerAppFont(MainActivity.java:168)
        at com.arthenica.mobileffmpeg.test.MainActivity.onCreate(MainActivity.java:123)
        at android.app.Activity.performCreate(Activity.java:7894)
        at android.app.Activity.performCreate(Activity.java:7881)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Environment**
 - Platform:  Android
 - Architecture: [i dont know]
 - Source branch [sdl]
 - Android Studio version :4.1.1

I think it's in development, is there any way to run ffplay, I want to listen audio of edited audio on the fly! is there any solution? or alternative of this?

**Comment by tanersener** [comment]
That branch is not stable, don't expect anything from `ffplay` on it.

There is no player in this library, at the moment. You need to use other libraries for playing/previewing.

**Comment by iamkdblue** [comment]
@tanersener thanks for the response, can you suggest any other llibraries for playing/previewing audio, that will be highly appreciated.

**Comment by tanersener** [comment]
Well, I'm not using a library. I don't think I can suggest any of them.

**Comment by iamkdblue** [comment]
@tanersener Thanks!
