### ISSUE TITLE
App working just fine on the debug mode but it crashes on the Release Mode

### ISSUE THREAD

**Issue by e-shawakri** [tanersener/mobile-ffmpeg#676]
The library is working just fine while debugging but when I generate the Release APK file and test it. it crashes. when I've test the released APK it shows the following error.

```
    --------- beginning of crash
2021-02-10 00:36:28.846 22300-22628/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.emad.videosEditor, PID: 22300
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:318)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: java.lang.NoClassDefFoundError: <clinit> failed for class com.arthenica.mobileffmpeg.Config; see exception in other thread
        at com.arthenica.mobileffmpeg.Config.a(SourceFile)
        at c.b.a.a.doInBackground(SourceFile:1)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:762) 
```
**FFMPEG version: 4.4.LTS**

**Comment by AxitaKathiriya** [comment]
I am facing the same problem.

**Comment by AxitaKathiriya** [comment]
I am facing the same problem.

**Description**
App is Crashing When i use FFmpeg.Cancel().

**Expected behavior**
App will work fine in release mode. App should not crash.

**Current behavior**
What happened.

**Logs**
**Fatal Exception: java.lang.NoClassDefFoundError: com/arthenica/mobileffmpeg/Config
       at com.arthenica.mobileffmpeg.FFmpeg.cancel(FFmpeg.java:175)**

**Environment**
 - Platform: [Android]
 - Architectures: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64, armv7, arm64]
 - Source branch  [mobile-ffmpeg-full-gpl:4.4.LTS]
 - Android Studio version  [4.1.1]
 - Android OS [4.4.2]
